### PR TITLE
Update home page images

### PR DESCRIPTION
**Pull request by ghostbear**

### CODE REVIEW

**Comment by Soitora** [comment]
Should the extensions description be rewritten to better hint at the extensions system so people don't look at the image and see only 4 unknown sources?

Maybe replace Manga preview with manga info page or something, or the trackers page for a series?

**Comment by ghostbear** [comment]
> Maybe replace Manga preview with manga info page or something, or the trackers page for a series?

Can replace it with the track sheet

**Comment by Soitora** [comment]
Now the texts doesn't match the images, I'm wondering though if there's a better reader image to represent it than some 1s and 0s heart

**Comment by ghostbear** [comment]
How about swapping extension and tracking text, would that be better?

**Comment by arkon** [comment]
Is it just me, or is the positioning of the 2 tracking image slightly off?

**Comment by ghostbear** [comment]
> Is it just me, or is the positioning of the 2 tracking image slightly off?

Fixed

**Review by arkon — APPROVED** [review]

**Review by Soitora — APPROVED** [review]

**Pull request merged**
