### PR TITLE
add download-migration warning

### LINKED ISSUE #535: Guides: Clarify the state of downloaded manga when migrating to another source
Migrating to a different source does not migrate downloads, and unless user deletes the files are orphaned. Thus user should either delete existing downloads from the current source first then redownload from migrated source, or move the downloads to a local manga to read offline.

This isn't particularly intuitive for users nor its mentioned in the app (the orphan part especially)

### PR DESCRIPTION
**Pull request by Seishirou101**
closes #535

### CODE REVIEW

**Review by ghostbear — APPROVED** [review]
LGTM :+1: 

But it is a bit hard to read

**Comment by Seishirou101** [comment]
> 
> 
> LGTM 👍
> 
> But it is a bit hard to read

hmmm, maybe something like this is better then? 
change

**Comment by ghostbear** [comment]
> > LGTM +1
> > But it is a bit hard to read
> 
> hmmm, maybe something like this is better then?
> change

```
Downloaded chapter do not transfer with migrations.

Migrations with downloaded chapter may leave the download behind. You will need to remove these manually with a file manager.
```
Maybe?

**Comment by Seishirou101** [comment]
> 
> 
> > > LGTM +1
> > > But it is a bit hard to read
> > 
> > 
> > hmmm, maybe something like this is better then?
> > change
> 
> ```
> Downloaded chapter do not transfer with migrations.
> 
> Migrations with downloaded chapter may leave the download behind. You will need to remove these manually with a file manager.
> ```
> 
> Maybe?

Yeah, I think that sounds good. I did downloaded chapter(s) without the parentheses though. Or do you think I should leave them singular?

**Comment by ghostbear** [comment]
There will probably be one or more downloaded chapters so doing parentheses is probably better

**Comment by Seishirou101** [comment]
sounds good, it has been added

**Pull request merged**
