### PR TITLE
Update document: Remove unnecessary sections & Add extension FAQ mention

### PR DESCRIPTION
**Pull request by YeiserDeveloper**
This pull request includes the following changes:

- Removal of unnecessary sections about MangaDex, Mangakakalot, Manganelo, Mangabat, Mangairo, and MangaPark.
- Addition of a mention regarding extension-specific FAQs and guides.

These modifications aim to streamline the document by removing irrelevant information and highlighting the availability of FAQs and guides for extensions. This improves the overall clarity and user experience of the document.

Please review and merge these changes at your convenience. Thank you!

### CODE REVIEW

**Comment by YeiserDeveloper** [comment]
This pull request includes the following changes:

- Removal of unnecessary sections about MangaDex, Mangakakalot, Manganelo, Mangabat, Mangairo, and MangaPark.
- Addition of a mention regarding extension-specific FAQs and guides.

These modifications aim to streamline the document by removing irrelevant information and highlighting the availability of FAQs and guides for extensions. This improves the overall clarity and user experience of the document.

Please review and merge these changes at your convenience. Thank you!

**Comment by scb261** [comment]
Don't include `package-lock.json` changes with the site content changes. If you actually want to make some changes to it - make a different branch with those changes and open a separate pull request from that branch.

**Comment by YeiserDeveloper** [comment]
Thank you for the feedback! I apologize for including the package-lock.json changes in this pull request. I will make sure to separate the changes and create a new branch for any modifications to package-lock.json in the future.

Regarding your advice for future changes, I completely agree. It would be more appropriate to keep the main branch in sync with the upstream and create separate branches for making changes. This way, we can easily pull changes from upstream without overwriting the local main branch.

Once again, thank you for the guidance. I will address these points and make the necessary adjustments.

**Comment by loocool2** [comment]
I don't think this PR makes sense as-is, you've removed the sections about each extension but in your new section you say there's extension specific guides but not where to find this extension-specific FAQ at all. 
Most extensions don't need any guides at all, so mentioning that an extension *may* have a FAQ and letting the user figure out where to find it, if it even has one, isn't very user-friendly.
If you're going to remove the extension-specific sections, I'd add some way to read the readme.md files from the tachiyomi-extensions repo into the site somehow so users can discover which ones have an extension-specific faq without needing to poke around in the repo.

**Comment by arkon** [comment]
Would need to revive #961 before removing that info, or at least just linking to things manually.

**Pull request closed without merging**
