### PR TITLE
Fix redirects

### PR DESCRIPTION
**Pull request by Soitora**
Maybe fix redirects?

### CODE REVIEW

**Comment by Soitora** [comment]
Hmm still redirects but gives `404` until page is refreshed, in local enviroment this works flawlessly. Maybe use Cloudflare for 301 for Permanent Redirects? Or anyone knows another solution to 301 redirecting?

**Comment by arkon** [comment]
Can we not just update whatever old references there are and not have redirects?

**Comment by Soitora** [comment]
> Can we not just update whatever old references there are and not have redirects?

We can, but Google will whine on us but I guess that's fine

**Comment by Soitora** [comment]
> Can we not just update whatever old references there are and not have redirects?

We can, but Google will whine on us but I guess that's fine

**Comment by Soitora** [comment]
Seems that doing a simple redirect then using dehydrate will fix the 404s

**Review by arkon — APPROVED** [review]

**Comment by arkon** [comment]
> Rebuilding package-lock didn't solve conflict, what's the best way to fix?

Did you rebase on top of master first?

**Review by arkon — APPROVED** [review]

**Pull request merged**
