### PR TITLE
Update project README

### PR DESCRIPTION
**Pull request by Soitora**
Adds repository cards.

### CODE REVIEW

**Review by ghostbear — COMMENTED** [review]
Dark theme cards look a bit odd with light theme GitHub

**Comment by Soitora** [comment]
Using [this](https://github.com/StylishThemes/GitHub-Dark) should be obligatory until we get official :)

**Review by ghostbear — COMMENTED** [review]
Sure, but I would rather prefer light theme until then. I don't think everyone is using a dark theme on GitHub

**Comment by Soitora** [comment]
Fine, I'll leave it at default :(

**Review by ghostbear — APPROVED** [review]

**Pull request merged**
