### PR TITLE
Fix weird clipping in Help section

### PR DESCRIPTION
**Pull request by GHOSTBEAR**
Fixes weird clipping on the Discord card when screen is narrow
Current: 
image
After:
image

### CODE REVIEW

**Comment by arkon** [comment]
I'd rather it actually pad/align to a grid properly. Not sure if @Soitora has thoughts about it.

**Comment by Soitora** [comment]
A real grid might be better for sure, if someone wants to refactor my code then I'd appreciate that. I'm not great at making grids/responsive layouts

**Comment by GHOSTBEAR** [comment]
image
I change it to display as a grid instead and all cards height follows to the tallest one

**Comment by Soitora** [comment]
I didn't notice until now but, can you sneak in a hover fix for the border moving the content?
Most likely because it's 2px on hover and 1px on static

**Comment by GHOSTBEAR** [comment]
@Soitora it should be fixed now

**Comment by Soitora** [comment]
Perfect

**Pull request merged**
