### PR TITLE
Very Important addition to TachiAZ page

### PR DESCRIPTION
**Pull request by az4521**
critical fix of missing functionality

### CODE REVIEW

**Comment by AbdullahM0hamed** [comment]
Mission level: Critical!

**Comment by AbdullahM0hamed** [comment]
Thank you for this good sir.

**Comment by Soitora** [comment]
I'll merge it in protest.

**Comment by AbdullahM0hamed** [comment]
Az is ushering a new era of memes! I love it😂😂😂😂

**Pull request merged**
