### PR TITLE
Update to NPM 7 in build script

### PR DESCRIPTION
**Pull request by ghostbear**
This:
- updates NPM to v7
- adds a cache for dependencies

We had some issues with NPM 6 on the rewrite project and NPM 7 solved the issues we experienced. So to not have any more conflicts with NPM we thought we might as well update to NPM 7 here too

### CODE REVIEW

**Review by Soitora — APPROVED** [review]
I know it worked for ours so I can approve, but maybe @arkon has something else to say

**Comment by arkon** [comment]
Maybe we should upgrade Node too?

**Comment by Soitora** [comment]
There are two dependencies that yell the following:
```js
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
```
Which is why we kept it at NodeJS 12 for now, and NodeJS 13 seems like a weird upgrade to do

**Comment by arkon** [comment]
Isn't LTS 14 or something now? It was just a thought since a newer version might have npm7 bundled anyway.

This is fine as-is though.

**Comment by ghostbear** [comment]
Node 14, which is LTS, still includes NPM 6

**Review by arkon — APPROVED** [review]

**Pull request merged**
