### PR TITLE
Attempt to fix ESlint Errors on Netlify

### PR DESCRIPTION
**Pull request by Soitora**
Move `npm run lint` to outside of the `npm run build` script.
Fix ESLint errors Local, same error showing in Netlify console.
Add a new `npm run test` script, replacing the old "lint and build"

### CODE REVIEW

**Comment by Soitora** [comment]
First in a while to succeed

image

**Comment by arkon** [comment]
I'm not sure just skipping it really qualifies as fixing?

**Comment by arkon** [comment]
Superseded by #1025

**Comment by Soitora** [comment]
> I'm not sure just skipping it really qualifies as fixing?

The fix was actually the quote change, not the "while I am at it" script changes

**Comment by arkon** [comment]
The quote changes aren't actually relevant, the linting just never runs if you check the deployment build logs.

Regardless, you just need to use a newer version of Node.

**Pull request closed without merging**
