### PR TITLE
Add DummyKiss for FAQ download

### PR DESCRIPTION
**Pull request by Soitora**
As requested by Support staff, adding linkable DummyKiss.

Although GitHub certainly isn't a file host per-se, a file or two shouldn't be a big issue.

### CODE REVIEW

**Comment by arkon** [comment]
It already complains that we're using GH Pages to host files. We should considering throwing these into a separate branch or repo, maybe?

**Comment by Soitora** [comment]
A seperate repo might be too much for a few files.
Branch maybe, could that still be easily tied to the `tachiyomi.org` domain, or do you mean to use the `raw.github` links?

**Comment by arkon** [comment]
> or do you mean to use the `raw.github` links?

Yeah, that.

**Comment by Soitora** [comment]
So a branch called `files` with a `README.md`, `LICENSE` and the files, at top level, or do you have a better idea?

**Comment by arkon** [comment]
Don't really need the README or LICENSE files. Just make sure it's an orphan branch, similar to `repo` in the extensions repo.

**Comment by Soitora** [comment]
Alright, and is this just for DummyRock/DummyKiss files-ish or do you intend for the video files too?

**Comment by arkon** [comment]
We can start off with the DummyKiss files first.

**Comment by Soitora** [comment]
Done, should maybe protect so that branches can't be created by anyone, seeing many of the PRs done here by others being branches here instead of branches on their own forks

**Pull request closed without merging**
