### PR TITLE
update j2k banner

### LINKED ISSUE #625: update j2k page with new app screenshots
as of v1.0.16, multiple changes have been made including the addition of the new toolbar

### PR DESCRIPTION
**Pull request by OncePunchedMan**
Closes #625

### CODE REVIEW

**Comment by arkon** [comment]
We probably want to avoid showing any specific sources.

**Comment by OncePunchedMan** [comment]
> We probably want to avoid showing any specific sources.

i chose mangaplus as source since it's official. also the sources on extension tab aren't the installed ones

**Comment by Soitora** [comment]
> > We probably want to avoid showing any specific sources.
> 
> i chose mangaplus as source since it's official.

That could be an issue (especially since on F-droid I *think* they mentioned seeing the Webtoons.com source), which is why the new vanilla banner looks like this:
App banner

**Comment by OncePunchedMan** [comment]
so no extension tab anymore and local source in manga details page?

**Comment by Soitora** [comment]
Perhaps, that's the safest bet

**Comment by arkon** [comment]
Whoops I forgot to respond, but yes to what Soi said.

We should update the other images too, including the one on the main page.

**Comment by ghostbear** [comment]
There are some videos where we show how users install/use extensions. Should we also update the video to use something that is maybe self-hosted like Komga?

**Comment by OncePunchedMan** [comment]
correct, if we decide to completely remove sources then we should update all banners

**Review by arkon — APPROVED** [review]

**Review by Soitora — APPROVED** [review]
Three approvals, why not

**Pull request merged**
