### PR TITLE
Update reader settings

### PR DESCRIPTION
**Pull request by ghostbear**
- Rearranged after reader setting in app
- Added "Invert Tapping"
- Added "Show content in cutout area"
- Added "Side padding"
- Added "Animate page transitions"
- Renamed "Default viewer" -> "Default reading mode"

### CODE REVIEW

**Review by Soitora — APPROVED** [review]

**Comment by ghostbear** [comment]
Don't merge this it seems like I missed something when doing the rebase

**Comment by Soitora** [comment]
That's fine it's better to approve and let the PR author merge 👍

**Comment by ghostbear** [comment]
Think I removed all duplicates. @Soitora could you give it a quick look just to double check it?

**Comment by Soitora** [comment]
I can check soon when my Japanese lessons are over

**Comment by Soitora** [comment]
Maybe "Page transitions" should be next to "Animate page transitions", or are they that far away in the app as well?

**Comment by ghostbear** [comment]
Seems like "Page transition" has been renamed to "Animated Page transition", because I can not find it the app and they have the same description

**Comment by Soitora** [comment]
Maybe cross check what options are as they should be?

**Comment by ghostbear** [comment]
They all seem to be there now in order and "Page transition" was renamed to "Animated page transitions"

**Comment by Soitora** [comment]
LGTM

**Pull request merged**
