### PR TITLE
Descriptions for Reader settings

### PR DESCRIPTION
**Pull request by GHOSTBEAR**
## TODO
- [x] Add images for Scale Type
- [x] Add images for Zoom start position
- [x] Add images for Background color
- [x] Add images for Crop border
- [x] Compress images

## 
I'm open for improvements to setting descriptions.

### CODE REVIEW

**Comment by GHOSTBEAR** [comment]
@Soitora I will drop the carousel and use **expander** for now

**Comment by Soitora** [comment]
Sad, you didn't find any way of making it work?

**Comment by GHOSTBEAR** [comment]
I did not find a way for vue-carousel to work. But I just tried pure CSS with [Gallery](http://benschwarz.github.io/gallery-css/) which seems to work by just importing it
gallery

**Comment by Soitora** [comment]
Have you been able to test its compatibility with mobile devices?

**Comment by GHOSTBEAR** [comment]
Yes it works on mobile

**Pull request merged**
