### PR TITLE
Increased extensions list performance

### PR DESCRIPTION
**Pull request by yegorgunko**
Performance has been improved thanks to [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) and a package [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller) which is a wrapper for observer.

### CODE REVIEW

**Comment by yegorgunko** [comment]
@ghostbear 'virtual scroll' should remove elements that aren't currently visible freeing up the DOM tree and thus boosting lists performance.
The hard thing in our particular case is groups. Since they have own loop. This package doesn't work well sometimes because of that. But as far as I could see, it doesn't keep all of the elements in the DOM which is it's purpose.

I will look into ways of implementing virtual scroll without external packages and for it to be able to work with our use case: groups.

**Comment by yegorgunko** [comment]
Well, I investigated a lot about virtual scrolling technique and I can say it is quite complicated.
For now I'm thinking of using a method that relies on absolute positioning / top padding (thanks [Vuetify](https://github.com/vuetifyjs/vuetify) for initial idea). To summarize what can be done in order to achieve virtual scroll:

1. Creating a container which will be overflowed and which will have `relative` positioning
2. Creating a list container which has a height of `totalItems * itemHeight`
3. Creating a list items which will have `absolute` positioning and will be generated by Vue having dynamic `top` style. Their top offset will be calculated based on the `scrollTop` value of the list.

By using such an approach, the DOM tree will have only the elements that are in the viewport while preserving the original list length and making it possible to scroll.
So, in general: for the user it will look just like an ordinary list with a scrollbar, but in the DOM there will be only a few elements rendered.

I'm finding it quite hard to implement for now, but I will look into it more.

**Comment by yegorgunko** [comment]
@ghostbear I've created a sandbox with my own virtual scroll implementation
It shows exactly what virtual scroll is about. It features a list with 100000 items.

https://codesandbox.io/s/vue-virtual-scroll-lemle

**Comment by ghostbear** [comment]
Great thanks helps a lot with understanding what it does :+1: 

Just so you know the reason why I asked if it can be done without a package is because we are currently rewriting the site and it doesn't use the same framework. So it would just add more work if another package was added and it would need to be rewritten to work with it

**Comment by yegorgunko** [comment]
@ghostbear is it gonna still be Vue? Maybe Vuepress v2?

**Comment by ghostbear** [comment]
It gonna still be Vue but with Gridsome instead of Vuepress

**Comment by yegorgunko** [comment]
Well, in the end, there is an issue with calculating dynamic height of the list.
It is caused by async data retrieval. Even `$nextTick` doesn't work, so for now I don't know how to implement the scroll in current situation.

Maybe on a new framework base there will be a clean way to do it.

**Pull request closed without merging**
