### PR TITLE
Add feature list for the Tachiyomi-J2K fork

### PR DESCRIPTION
**Pull request by joseph619**
Added feature list for J2k

### CODE REVIEW

**Comment by Soitora** [comment]
This entire section, maybe do more focused parts in the bullet points, maybe make it look nice, now it's a cluttered mess

image

Also, don't use headers for either the GitHub or Download link, it worked when there was nothing else but not now, only use headers when they're necessary. 

You could for example also change `#### Feature list:` to `### Features`

**Comment by joseph619** [comment]
Well, I copied and pasted the bullet points it directly from Jay's repo, I don't know if he would mind if I changed the wording. 

I will fix the header soon.

**Comment by Soitora** [comment]
The point was to make it look good for the website, which I'm sure even he could take in and improve to his own later

**Comment by joseph619** [comment]
Made various changes

**Comment by Soitora** [comment]
You still haven't taken what I said and tried to implement it (except the indented bullet points)
A lot of stuff still looks awkward (for example image below)
image

**Comment by Soitora** [comment]
Good :)
I am looking into different ways to present data such as this in the future, maybe through the help of plugins.
Are you able to do something similiar for the other forks?

**Comment by joseph619** [comment]
Sure, I can do it for everything except Neko :)

**Pull request merged**
