### PR TITLE
Add a link to the local source JSON generator tool

### PR DESCRIPTION
**Pull request by alessandrojean**
I created a [tool](https://tachi-local.netlify.app) that allows the user to create and edit the `details.json` for using in the local source.

I think it's interesting to link it on the website to allow the users to make use of it.

The URL have some `utm` parameters, but they can be removed if needed.

### CODE REVIEW

**Comment by Soitora** [comment]
LGTM, awaiting further feedback
Are you not able to input multiple authors/artists with your tool ? It's not implied (neither is it in our website docs)

**Review by Soitora — APPROVED** [review]

**Comment by alessandrojean** [comment]
Multiple authors/artists can be entered with any type of separator (`,`, `&`, `;`). It's manual.

I can probably indicate that with a help text though.

**Review by arkon — APPROVED** [review]
This could probably be added within this repo itself if you want (and ultimately in the app), but I'm with this as-is too.

**Comment by alessandrojean** [comment]
> This could probably be added within this repo itself if you want (and ultimately in the app), but I'm with this as-is too.

It was my initial idea, but I thought making it separate first would be good to catch some new ideas and improvements to the tool. Later it can be integrated into the website, I am planning to work on it.

**Pull request merged**
