### PR TITLE
Backup reader and converter

### PR DESCRIPTION
**Pull request by FramboisePi**
This pull request implements a Paperback and Tachiyomi backup reader and converter.

### Reader
The reader allows to display the content of a backup.
> **The backup content grid**:
> Capture d’écran 2021-09-22 à 19 03 09
>
> **Dialog with information about a particular title**:
> Capture d’écran 2021-09-22 à 19 03 22

### Converter
The tool allows to convert between Tachiyomi and Paperback backups.

---

These two tools are based on the new converter which code can be found on this [temporary repository](https://github.com/FramboisePi/Tachiyomi-To-Paperbackup-Converter) or in the [corresponding pull request](https://github.com/Paperback-iOS/Tachiyomi-To-Paperbackup-Converter/pull/3).
Every action now happens in the user browser using `backupConverter.js`: the browserified, tinified code exported using the previous repository.

@Soitora asked at the beginning if the numerous files could be merged into 3 components. If that would definitely be possible, I tried here to put them into a `.vuepress/components/Backup` folder. I can change this if you prefer.

I was not sure where to put the tools. I currently added two sections in `guide/backups` and put the converter/reader page in a `tools` folder. If you know a better place for this, we could improve the page location.

Also adding a way to export Tachiyomi backups to a json file could be easy, I don't know if that would be useful.

Every comments ideas and suggestions would be useful and welcome!

### CODE REVIEW

**Comment by arkon** [comment]
@FramboisePi Were you intending on returning this at some point?

**Comment by Soitora** [comment]
If not, Paperback website can host it all if it work for you, since we're abandoning Vue in general

**Comment by arkon** [comment]
We can always split it off to its own repo and still serve it under the tachiyomi.org domain if need be.

**Comment by ghostbear** [comment]
It could be added to the monorepo, and still use Vue, whenever we get to a state where the new website can be deployed

**Pull request closed without merging**
